#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-boltdb-bolt
Version  : 144418e1475d8bf7abbdc48583500f1a20c62ea7
Release  : 1
URL      : https://github.com/boltdb/bolt/archive/144418e1475d8bf7abbdc48583500f1a20c62ea7.tar.gz
Source0  : https://github.com/boltdb/bolt/archive/144418e1475d8bf7abbdc48583500f1a20c62ea7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : go

%description
Bolt [![Coverage Status](https://coveralls.io/repos/boltdb/bolt/badge.svg?branch=master)](https://coveralls.io/r/boltdb/bolt?branch=master) [![GoDoc](https://godoc.org/github.com/boltdb/bolt?status.svg)](https://godoc.org/github.com/boltdb/bolt) ![Version](https://img.shields.io/badge/version-1.0-green.svg)
====

%prep
%setup -q -n bolt-144418e1475d8bf7abbdc48583500f1a20c62ea7

%build

%install
gopath="/usr/lib/golang"
library_path="github.com/boltdb/bolt"
rm -rf %{buildroot}
install -d -p %{buildroot}${gopath}/src/${library_path}/
for file in $(find . -iname "*.go" -o -iname "*.h" -o -iname "*.c") ; do
     echo ${file}
     install -d -p %{buildroot}${gopath}/src/${library_path}/$(dirname $file)
     cp -pav $file %{buildroot}${gopath}/src/${library_path}/$file
done


%files
%defattr(-,root,root,-)
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_386.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_amd64.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_arm.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_arm64.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_linux.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_openbsd.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_ppc.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_ppc64.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_ppc64le.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_s390x.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_unix.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_unix_solaris.go
/usr/lib/golang/src/github.com/boltdb/bolt/bolt_windows.go
/usr/lib/golang/src/github.com/boltdb/bolt/boltsync_unix.go
/usr/lib/golang/src/github.com/boltdb/bolt/bucket.go
/usr/lib/golang/src/github.com/boltdb/bolt/bucket_test.go
/usr/lib/golang/src/github.com/boltdb/bolt/cmd/bolt/main.go
/usr/lib/golang/src/github.com/boltdb/bolt/cmd/bolt/main_test.go
/usr/lib/golang/src/github.com/boltdb/bolt/cursor.go
/usr/lib/golang/src/github.com/boltdb/bolt/cursor_test.go
/usr/lib/golang/src/github.com/boltdb/bolt/db.go
/usr/lib/golang/src/github.com/boltdb/bolt/db_test.go
/usr/lib/golang/src/github.com/boltdb/bolt/doc.go
/usr/lib/golang/src/github.com/boltdb/bolt/errors.go
/usr/lib/golang/src/github.com/boltdb/bolt/freelist.go
/usr/lib/golang/src/github.com/boltdb/bolt/freelist_test.go
/usr/lib/golang/src/github.com/boltdb/bolt/node.go
/usr/lib/golang/src/github.com/boltdb/bolt/node_test.go
/usr/lib/golang/src/github.com/boltdb/bolt/page.go
/usr/lib/golang/src/github.com/boltdb/bolt/page_test.go
/usr/lib/golang/src/github.com/boltdb/bolt/quick_test.go
/usr/lib/golang/src/github.com/boltdb/bolt/simulation_test.go
/usr/lib/golang/src/github.com/boltdb/bolt/tx.go
/usr/lib/golang/src/github.com/boltdb/bolt/tx_test.go
